apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts
  template:
    metadata:
      labels:
        app: cts
    spec:
      containers:
      - name: cts
        image: harbor.mymemorylog.com/cts/cts:1.0.0-9fbfb185-8c1b-4d99-9a54-d42cfd59a96b
        ports:
        - containerPort: 3000