apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts
  template:
    metadata:
      labels:
        app: cts
    spec:
      containers:
      - name: cts
        image: harbor.mymemorylog.com/cts/cts:1.0.0-d3f81498-ee93-499a-a030-36e6a6efee9c
        ports:
        - containerPort: 3000