apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts
  template:
    metadata:
      labels:
        app: cts
    spec:
      containers:
      - name: cts
        image: harbor.mymemorylog.com/cts/cts:0.1.35ee4b32-d647-45c1-8d1a-c2f44c1f8672
        ports:
        - containerPort: 3000