apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cts
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'cts-namespace'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'