apiVersion: v1
kind: Secret
metadata:
  name: cts-infrastructure
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com:cts2782346/cts-infrastructure.git
