apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cts-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: cts.35.204.45.18.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cts
            port:
              number: 80